### ISSUE TITLE
Missing schema files

### ISSUE THREAD

**Issue by JimDanner** [thunderbird/webext-schemas#1]
Good to have the schemas in one place for quick download.

It seems a few are missing:

* proxy.json, for the [proxy API](https://webextension-api.thunderbird.net/en/latest/proxy.html)
* network_status.json, for the [networkStatus API](https://webextension-api.thunderbird.net/en/latest/networkStatus.html)
* captive_portal.json, for the [captivePortal API](https://webextension-api.thunderbird.net/en/latest/captivePortal.html)

In addition, there are some schemas whose usefulness I can't ascertain, mostly for monitoring and measuring the application and the extension. I wonder whether they're implemented in Thunderbird:

* activity_log.json, for the activityLog namespace
* geckoProfiler.json, for the geckoProfiler namespace
* telemetry.json, for the telemetry namespace

**Comment by jobisoft** [comment]
The proxy API will be removed from the documentation, since the API does not work for us. I filed [bug 1903727](https://bugzilla.mozilla.org/show_bug.cgi?id=1903727).

All the other APIs will be removed as well, because they are internal mozilla-only APIs (the add-on has to be signed by a special CA in order for them to work).

I am currently working on [webext-compat-data](https://github.com/thunderbird/webext-compat-data), which will be the central authority for "does this work for us". I think I will be able to release a first version in a couple of days.

After the webext-compat-data is available, this repo and the documentation will be updated. 

Note: Long term goal is to merge webext-compat-data into [browser-compat-data](https://github.com/mdn/browser-compat-data), but first we have to have the data, of course.

**Comment by jobisoft** [comment]
First version of [webext-compat-data](https://github.com/thunderbird/webext-compat-data) is out, this repo is using it as the only source of truth, and the documentation has been updated as well. 

All the schemas you mentioned are no longer considered compatible with Thunderbird and are no longer included.
